# Generated by Django 5.2.1 on 2025-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('authenticated_permission', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Read Only'), (2, 'Read and Write')], default=0)),
                ('team_permission', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Read Only'), (2, 'Read and Write')], default=0)),
                ('public_permission', models.BooleanField(default=False)),
            ],
        ),
    ]
