# Generated by Django 5.2.1 on 2025-06-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_like_user_alter_like_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
